### ISSUE TITLE
Fix Join.me icon

### ISSUE THREAD

**Issue by zimbatm** [smcllns/css-social-buttons#94]
I don't know why but the joinme.svg doesn't render properly. A lot of css has changed in 410fd6b144d4ff222bfd2eb52f40d22756736246 which either means that fontcustom has changed or the the joinme contributor has touched some of the css by hand.

/cc @suttonj

**Comment by barbosab** [comment]
This should be closed following merge of https://github.com/smcllns/css-social-buttons/pull/102

**Comment by zimbatm** [comment]
Thanks
